// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yolszwwuuranwwajognn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvbHN6d3d1dXJhbnd3YWpvZ25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjIzNzksImV4cCI6MjA3Mjc5ODM3OX0.GEzvm-yod-prjIUuI6Vbf_VMG9AKAaJgahTAg_s8dwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});